[package]
name = "coin-bot"
version = "0.1.0"
authors = ["raravel <youn@tree-some.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
